"""adding a source image

Revision ID: f12d436dd589
Revises: db7ff98de8f7
Create Date: 2021-03-26 01:03:16.358264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12d436dd589'
down_revision = 'db7ff98de8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('source_img', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'source_img')
    # ### end Alembic commands ###
